name: PowerShell Module Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Pester
      shell: pwsh
      run: |
        Install-Module Pester -Force -SkipPublisherCheck -Scope CurrentUser

    - name: Run Tests
      shell: pwsh
      run: |
        $testPath = Join-Path $PWD 'tests'
        Invoke-Pester -Path $testPath -CI
